/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanager;
/**
 *
 * @author georg
 */
public class AMSettingsDialog extends javax.swing.JDialog {

    private boolean result = false;
    /**
     * Creates new form AMSettingsDialog
     */
    public AMSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public boolean exec(){
        setVisible(true);
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        settingsTabbedPane = new javax.swing.JTabbedPane();
        serverSettingsScroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        serverLAbel = new javax.swing.JLabel();
        servetEdit = new javax.swing.JTextField();
        dnLabel = new javax.swing.JLabel();
        dnEdit = new javax.swing.JTextField();
        userBaseLabel = new javax.swing.JLabel();
        userBaseEdit = new javax.swing.JTextField();
        groupBaseLabel = new javax.swing.JLabel();
        groupBaseEdit = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        userSettingsPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        objectClassesEdit = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAttrTable = new javax.swing.JTable();
        groupSettingsPane = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        objectClassesEditGroup = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupAttrTable = new javax.swing.JTable();
        settingsAcceptButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        settingsRejectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Настройки программы");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0};
        getContentPane().setLayout(layout);

        settingsTabbedPane.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        settingsTabbedPane.setPreferredSize(new java.awt.Dimension(400, 300));

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        serverLAbel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        serverLAbel.setText("Адресс сервера LDAP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(serverLAbel, gridBagConstraints);

        servetEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        jPanel1.add(servetEdit, gridBagConstraints);

        dnLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dnLabel.setText("DN привязки:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(dnLabel, gridBagConstraints);

        dnEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(dnEdit, gridBagConstraints);

        userBaseLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        userBaseLabel.setText("База поиска пользователей:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(userBaseLabel, gridBagConstraints);

        userBaseEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        userBaseEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBaseEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(userBaseEdit, gridBagConstraints);

        groupBaseLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        groupBaseLabel.setText("База поиска групп:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(groupBaseLabel, gridBagConstraints);

        groupBaseEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(groupBaseEdit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(filler3, gridBagConstraints);

        serverSettingsScroll.setViewportView(jPanel1);

        settingsTabbedPane.addTab("Cервер", serverSettingsScroll);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Обьектные классы");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        objectClassesEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel2.add(objectClassesEdit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jDesktopPane1, gridBagConstraints);

        userAttrTable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        userAttrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Параметр", "Значение"
            }
        ));
        jScrollPane1.setViewportView(userAttrTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        userSettingsPane.setViewportView(jPanel2);

        settingsTabbedPane.addTab("Пользователи", userSettingsPane);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Обьектные классы");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        objectClassesEditGroup.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel3.add(objectClassesEditGroup, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jDesktopPane2, gridBagConstraints);

        groupAttrTable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        groupAttrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Параметр", "Значение"
            }
        ));
        jScrollPane2.setViewportView(groupAttrTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane2, gridBagConstraints);

        groupSettingsPane.setViewportView(jPanel3);

        settingsTabbedPane.addTab("Группы", groupSettingsPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(settingsTabbedPane, gridBagConstraints);

        settingsAcceptButton.setText("OK");
        settingsAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsAcceptButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        getContentPane().add(settingsAcceptButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        getContentPane().add(filler1, gridBagConstraints);

        settingsRejectButton.setText("Отмена");
        settingsRejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsRejectButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(settingsRejectButton, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-479)/2, 600, 479);
    }// </editor-fold>//GEN-END:initComponents

    private void userBaseEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBaseEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userBaseEditActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        result = false;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void settingsRejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsRejectButtonActionPerformed
        // TODO add your handling code here:
        result = false;
        this.dispose();
    }//GEN-LAST:event_settingsRejectButtonActionPerformed

    private void settingsAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsAcceptButtonActionPerformed
        // TODO add your handling code here:
        result = true;
        if (userAttrTable.isEditing())
              userAttrTable.getCellEditor().stopCellEditing();
        this.dispose();
    }//GEN-LAST:event_settingsAcceptButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField dnEdit;
    public javax.swing.JLabel dnLabel;
    public javax.swing.Box.Filler filler1;
    public javax.swing.Box.Filler filler2;
    public javax.swing.Box.Filler filler3;
    public javax.swing.JTable groupAttrTable;
    public javax.swing.JTextField groupBaseEdit;
    public javax.swing.JLabel groupBaseLabel;
    public javax.swing.JScrollPane groupSettingsPane;
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JDesktopPane jDesktopPane2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField objectClassesEdit;
    public javax.swing.JTextField objectClassesEditGroup;
    public javax.swing.JLabel serverLAbel;
    public javax.swing.JScrollPane serverSettingsScroll;
    public javax.swing.JTextField servetEdit;
    public javax.swing.JButton settingsAcceptButton;
    public javax.swing.JButton settingsRejectButton;
    public javax.swing.JTabbedPane settingsTabbedPane;
    public javax.swing.JTable userAttrTable;
    public javax.swing.JTextField userBaseEdit;
    public javax.swing.JLabel userBaseLabel;
    public javax.swing.JScrollPane userSettingsPane;
    // End of variables declaration//GEN-END:variables
}
