/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package accountmanager;

/**
 *
 * @author georg
 */
public class AMUserEditDialog extends javax.swing.JDialog {

    /**
     * Creates new form AMUserEditDialog
     */
    public AMUserEditDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        memberList = new javax.swing.JList();
        addMemberButton = new javax.swing.JButton();
        deleteMemberButton = new javax.swing.JButton();
        addAllMembersButton = new javax.swing.JButton();
        snEdit = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        givenNameEdit = new javax.swing.JTextField();
        ouEdit = new javax.swing.JComboBox();
        titleEdit = new javax.swing.JTextField();
        mailEdit = new javax.swing.JTextField();
        deleteAllMemberButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        snLabel = new javax.swing.JLabel();
        givenNameLabel = new javax.swing.JLabel();
        ouLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        cancelButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        deleteButton = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        saveButton = new javax.swing.JButton();
        roomNumberEdit = new javax.swing.JTextField();
        roomNumberLabel = new javax.swing.JLabel();
        telephoneNumberLabel = new javax.swing.JLabel();
        telephoneNumberEdit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Редактор пользователей");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                userEditDialogWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setViewportView(groupList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.48;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setViewportView(memberList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.48;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        addMemberButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1rightarrow.png"))); // NOI18N
        addMemberButton.setToolTipText("Добавить");
        addMemberButton.setMaximumSize(new java.awt.Dimension(32, 32));
        addMemberButton.setMinimumSize(new java.awt.Dimension(32, 32));
        addMemberButton.setPreferredSize(new java.awt.Dimension(32, 32));
        addMemberButton.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(addMemberButton, gridBagConstraints);

        deleteMemberButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1leftarrow.png"))); // NOI18N
        deleteMemberButton.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(deleteMemberButton, gridBagConstraints);

        addAllMembersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2rightarrow.png"))); // NOI18N
        addAllMembersButton.setToolTipText("Добавить все");
        addAllMembersButton.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(addAllMembersButton, gridBagConstraints);

        snEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(snEdit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filler1, gridBagConstraints);

        givenNameEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(givenNameEdit, gridBagConstraints);

        ouEdit.setEditable(true);
        ouEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(ouEdit, gridBagConstraints);

        titleEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(titleEdit, gridBagConstraints);

        mailEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(mailEdit, gridBagConstraints);

        deleteAllMemberButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2leftarrow.png"))); // NOI18N
        deleteAllMemberButton.setToolTipText("Удалить все");
        deleteAllMemberButton.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(deleteAllMemberButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filler2, gridBagConstraints);

        snLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        snLabel.setText("Фамилия");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(snLabel, gridBagConstraints);

        givenNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        givenNameLabel.setText("Имя Отчество");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(givenNameLabel, gridBagConstraints);

        ouLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        ouLabel.setText("Отдел");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(ouLabel, gridBagConstraints);

        titleLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        titleLabel.setText("Должность");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(titleLabel, gridBagConstraints);

        mailLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        mailLabel.setText("Электронная почта");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(mailLabel, gridBagConstraints);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler3);

        cancelButton.setText("Отмена");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);
        jPanel1.add(filler4);

        deleteButton.setText("Удалить");
        jPanel1.add(deleteButton);
        jPanel1.add(filler5);

        saveButton.setText("Сохранить");
        jPanel1.add(saveButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        roomNumberEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(roomNumberEdit, gridBagConstraints);

        roomNumberLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        roomNumberLabel.setText("Кабинет");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(roomNumberLabel, gridBagConstraints);

        telephoneNumberLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        telephoneNumberLabel.setText("Рабочий телефон");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(telephoneNumberLabel, gridBagConstraints);

        telephoneNumberEdit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(telephoneNumberEdit, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-636)/2, (screenSize.height-477)/2, 636, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void userEditDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_userEditDialogWindowClosing
        // TODO add your handling code here:
        result = 0;
        this.dispose();
    }//GEN-LAST:event_userEditDialogWindowClosing

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    int result=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addAllMembersButton;
    public javax.swing.JButton addMemberButton;
    public javax.swing.JButton cancelButton;
    public javax.swing.JButton deleteAllMemberButton;
    public javax.swing.JButton deleteButton;
    public javax.swing.JButton deleteMemberButton;
    public javax.swing.Box.Filler filler1;
    public javax.swing.Box.Filler filler2;
    public javax.swing.Box.Filler filler3;
    public javax.swing.Box.Filler filler4;
    public javax.swing.Box.Filler filler5;
    public javax.swing.JTextField givenNameEdit;
    public javax.swing.JLabel givenNameLabel;
    public javax.swing.JList groupList;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField mailEdit;
    public javax.swing.JLabel mailLabel;
    public javax.swing.JList memberList;
    public javax.swing.JComboBox ouEdit;
    public javax.swing.JLabel ouLabel;
    public javax.swing.JTextField roomNumberEdit;
    public javax.swing.JLabel roomNumberLabel;
    public javax.swing.JButton saveButton;
    public javax.swing.JTextField snEdit;
    public javax.swing.JLabel snLabel;
    public javax.swing.JTextField telephoneNumberEdit;
    public javax.swing.JLabel telephoneNumberLabel;
    public javax.swing.JTextField titleEdit;
    public javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
